marketplace:
  mercadolibre:
    id: mercadolibre
    country:
      co:
        name: Colombia
        origin: https://www.mercadolibre.com.co
        url: https://www.mercadolibre.com.co/c/{CATEGORY_ID}
        url_categories: https://www.mercadolibre.com.co/categorias#menu=categories
      mx:
        name: Mexico
        origin: https://www.mercadolibre.com.mx
        url: https://www.mercadolibre.com.mx/c/{CATEGORY_ID}
        url_categories: https://www.mercadolibre.com.mx/categorias#menu=categories
    queries:
      categorypage_subcategories_links: '.ui-search-filter-dl:nth-child(3) > .ui-search-filter-container > a'
      list_products: '.ui-search-layout'
      product_container: 'ui-search-layout__item'
      product_container_tag: 'li'
      product_title: 'ui-search-item__title'
      product_title_tag: 'h2'
      product_url: '.ui-search-item__group__element'
      product_price_symbol: 'price-tag-symbol'
      product_price: 'price-tag-fraction'
      product_price_discount: 'ui-search-price__discount'
      product_best_seller: 'ui-search-item__highlight-label--best_seller'
      product_promotional: '.ui-search-item__ad-label--blue'
      page_categories: '.categories__container > .categories__title'
      page_subcategories: '.desktop__view-child > a'
  linio:
    id: linio
    country:
      co:
        name: Colombia
        origin: https://www.linio.com.co
        url: https://linio.com.co/c/deportes
        url_categories: https://www.linio.com.co
      mx:
        name: Mexico
        origin: https://www.linio.com.mx
        url: https://linio.com.mx/c/deportes
        url_categories: https://www.linio.com.mx
    queries:
      categorypage_subcategories_links: '.catalogue-list > ul > li.active > ul > li > a'
      list_products: '.switchable-product-container'
      product_container: 'catalogue-product'
      product_container_tag: 'div'
      product_title: 'title-section'
      product_title_tag: 'span'
      product_url: '.catalogue-product > a'
      product_price_symbol: ''
      product_price: 'price-main-md'
      product_price_discount: 'discount'
      product_best_seller: 'ui-search-item__highlight-label--best_seller'
      product_promotional: '.catalogue-sponsored-product'
      page_categories: '.main-menu .nav > li'
