marketplace:
  mercadolibre:
    id: mercadolibre
    engine:
      catalog: scrapy
      products: beautifulsoup4
    country:
      co:
        name: Colombia
        origin: https://www.mercadolibre.com.co
        url_categories: https://www.mercadolibre.com.co/categorias
      cl:
        name: Chile
        origin: https://www.mercadolibre.cl
        url_categories: https://www.mercadolibre.cl/categorias
      mx:
        name: Mexico
        origin: https://www.mercadolibre.com.mx
        url_categories: https://www.mercadolibre.com.mx/categorias
    queries:
      categories_container_level_1: 'div.categories__container'
      category_href_level_1: 'h2.categories__title > a'
      category_name_level_1: 'h2.categories__title > a::text'
      category_subcategories_level_1: 'ul.categories__list li'
      categories_container_level_2: 'div.desktop__view-child'
      category_href_level_2: 'a'
      category_name_level_2: 'div.category-list__permanlink > h3::text'
      category_subcategories_level_2: 'ul.desktop__view-ul > li'
      categories_container_level_3: 'ul.desktop__view-ul > li'
      category_href_level_3: 'a'
      category_name_level_3: 'h4::text'
      category_subcategories_level_3: ''
      categories_container_level_4: '.ui-search-filter-dl:nth-child(3) > dd.ui-search-filter-container'
      category_href_level_4: 'a.ui-search-link'
      category_name_level_4: 'a.ui-search-link > span.ui-search-filter-name::text'
      category_subcategories_level_4: ''
      # ! OLD
      categorypage_subcategories_links: '.ui-search-filter-dl:nth-child(3) > .ui-search-filter-container > a'
      list_products: '.ui-search-layout'
      product_container: 'ui-search-layout__item'
      product_container_tag: 'li'
      product_title: 'ui-search-item__title'
      product_title_tag: 'h2'
      product_url: '.ui-search-item__group__element'
      product_price_symbol: 'price-tag-symbol'
      product_price: 'price-tag-fraction'
      product_price_discount: 'ui-search-price__discount'
      product_best_seller: 'ui-search-item__highlight-label--best_seller'
      product_promotional: '.ui-search-item__ad-label--blue'
      page_categories: '.categories__container > .categories__title'
      page_subcategories: '.desktop__view-child > a'
      section_pagination: 'ul.ui-search-pagination > li'
  linio:
    id: linio
    country:
      co:
        name: Colombia
        origin: https://www.linio.com.co
        url_categories: https://www.linio.com.co
      mx:
        name: Mexico
        origin: https://www.linio.com.mx
        url_categories: https://www.linio.com.mx
    queries:
      categorypage_subcategories_links: '.catalogue-list > ul > li.active > ul > li > a'
      list_products: '.switchable-product-container'
      product_container: 'catalogue-product'
      product_container_tag: 'div'
      product_title: 'title-section'
      product_title_tag: 'span'
      product_url: '.catalogue-product > a'
      product_price_symbol: ''
      product_price: 'price-main-md'
      product_price_discount: 'discount'
      product_best_seller: 'ui-search-item__highlight-label--best_seller'
      product_promotional: '.catalogue-sponsored-product'
      page_categories: '.main-menu .nav > li'

  
